### ISSUE TITLE
帮助文档中，符号中英文混用

### ISSUE THREAD

**Issue by sbcxk** [Wang-zhechao/solitaire#1]
根据代码校验，应该都使中文冒号
![image](https://github.com/Wang-zhechao/solitaire/assets/67060479/5527a338-9163-47e1-b369-9bb82a2dae92)

**Comment by Wang-zhechao** [comment]
感谢指正 错误已修复
https://github.com/Wang-zhechao/solitaire/commit/d475c80ea904fb42659c447af0bdc1406af28374
